In [ ]:
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "da5fd2ab",
   "metadata": {
    "tags": []
   },
   "source": [
    "## System_of_Linear_Equations\n",
    "\n",
    "##### By: Justin Alain B. Monreal\n",
    "<br>\n",
    "\n",
    "### ASSIGNMENT 1\n",
    "<br>\n",
    "Given this code for Forward Elimination:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "2001708e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "# Pythonic Solutions\n",
    "# the following functions are the steps involved in forward elimination\n",
    "\n",
    "def RowSwap(A,k,l):\n",
    "# =============================================================================\n",
    "#     A is a NumPy array.  RowSwap will return duplicate array with rows\n",
    "#     k and l swapped.\n",
    "# =============================================================================\n",
    "    m = A.shape[0]  # m is number of rows in A\n",
    "    n = A.shape[1]  # n is number of columns in A\n",
    "    \n",
    "    B = np.copy(A).astype('float64')\n",
    "        \n",
    "    for j in range(n):\n",
    "        temp = B[k][j]\n",
    "        B[k][j] = B[l][j]\n",
    "        B[l][j] = temp\n",
    "        \n",
    "    return B\n",
    "\n",
    "def RowScale(A,k,scale):\n",
    "# =============================================================================\n",
    "#     A is a NumPy array.  RowScale will return duplicate array with the\n",
    "#     entries of row k multiplied by scale.\n",
    "# =============================================================================\n",
    "    m = A.shape[0]  # m is number of rows in A\n",
    "    n = A.shape[1]  # n is number of columns in A\n",
    "    \n",
    "    B = np.copy(A).astype('float64')\n",
    "\n",
    "    for j in range(n):\n",
    "        B[k][j] *= scale\n",
    "        \n",
    "    return B\n",
    "\n",
    "def RowAdd(A,k,l,scale):\n",
    "# =============================================================================\n",
    "#     A is a numpy array.  RowAdd will return duplicate array with row\n",
    "#     l modifed.  The new values will be the old values of row l added to \n",
    "#     the values of row k, multiplied by scale.\n",
    "# =============================================================================\n",
    "    m = A.shape[0]  # m is number of rows in A\n",
    "    n = A.shape[1]  # n is number of columns in A\n",
    "    \n",
    "    B = np.copy(A).astype('float64')\n",
    "        \n",
    "    for j in range(n):\n",
    "        B[l][j] += B[k][j]*scale\n",
    "        \n",
    "    return B"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0318ff41",
   "metadata": {},
   "source": [
    "Complete the process of determining the solution by creating a function or steps of function that will automate backward substitution."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "cbd28b8f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# code for the automation of backward substitution\n",
    "def BackwardSubstitution(U, b):\n",
    "    n = U.shape[0]  # Number of rows/columns in U\n",
    "    x = np.zeros(n)  # Initialize the solution vector\n",
    "\n",
    "    for i in range(n - 1, -1, -1):\n",
    "        x[i] = b[i]\n",
    "        for j in range(i + 1, n):\n",
    "            x[i] -= U[i][j] * x[j]\n",
    "        if U[i][i] != 0:\n",
    "            x[i] /= U[i][i]\n",
    "        else:\n",
    "            x[i] = 0  # Set x[i] to 0 as an example\n",
    "\n",
    "    return x\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a032a47a",
   "metadata": {
    "tags": []
   },
   "source": [
    "### ASSIGNMENT 2\n",
    "<br>\n",
    "1. Provide reasons why each of the following equations is, or is not, a linear equation.\n",
    "<br>\n",
    "    a. $\\cos{\\theta}x+4y+z = \\sqrt{3}$\n",
    "        <br> - This equation qualifies as linear because it adheres to the essential criteria of a linear equation. All variables (x, y, and z) are raised to the first power, and they are combined with constant coefficients. No nonlinearity like square roots or trigonometric functions is involved in the equation's formulation.\n",
    "        <br><br>\n",
    "    b. $ \\cos{x}4y+z = \\sqrt{3} $\n",
    "        <br> - Unlike a linear equation, this equation is nonlinear. The presence of $ \\cos{x} $ violates the primary condition of linear equations, which mandates that variables appear with a power of 1 (without exponents or functions applied to them).\n",
    "        <br><br>\n",
    "    c. $ x^{-1}+7y+z = \\sin{(\\frac{\\pi}{2})} $\n",
    "        <br> - This equation is nonlinear due to the presence of the variable x raised to the power of -1, which doesn't adhere to the fundamental linearity criterion. Although $\\sin{(\\frac{\\pi}{2})}$ is a linear constant, it doesn't render the entire equation linear.\n",
    "        <br><br>\n",
    "    d. $ x^1+y^1+z^1=0 $\n",
    "        <br> - A linear equation, as all three variables (x, y, and z) possess a power of 1, a characteristic of linear equations. These variables are simply combined with coefficients of 1, without any additional nonlinear operations like square roots or trigonometric functions. Additionally, the right-hand side is a constant value, which aligns with the nature of a linear equation.\n",
    " <br><br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5b566667",
   "metadata": {},
   "source": [
    "2. Find the solutions to the linear equations: <br>\n",
    "a) $2x_1+3x_2 =5$"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7c092bb6-90df-49da-98dd-fe995b0c8ecf",
   "metadata": {},
   "source": [
    "Manual Solution:\n",
    "$\n",
    "2x_1+3x_2 =5 \\\\\n",
    "\\frac{2x_1}{2} = \\frac{5 - 3x_2}{2} \\\\\n",
    "\\boxed{x_1 = \\frac{5}{2} - \\frac{3}{2}x_2}\n",
    "$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d12dd785",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result: \n",
      "[(5/2 - 3*x2/2, x2)]\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "import sympy as sp\n",
    "x1, x2 = sp.symbols('x1 x2')\n",
    "equation = sp.Eq(2*x1 + 3*x2, 5)\n",
    "solution = sp.solve(equation, (x1, x2))\n",
    "\n",
    "print(\"Result: \")\n",
    "print(solution)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6adfc030-7933-419c-95fb-f6a06142d98d",
   "metadata": {},
   "source": [
    "<br>b) $4x_1+3x_2+2x_3 = 1$"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "78a59193-e5aa-4e43-9b54-648c7f2744d7",
   "metadata": {},
   "source": [
    "Manual Solution:\n",
    "$\n",
    "4x_1+3x_2+2x_3 = 1 \\\\\n",
    "\\frac{4x_1}{4} = \\frac{1 - 3x_2 - 2x_3}{4} \\\\\n",
    "\\boxed{x_1 = \\frac{1}{4} - \\frac{3}{4}x_2 - \\frac{1}{2}x_3}\n",
    "$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6d72f328-ff98-4a1d-b3c1-586018a000a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result: \n",
      "[(-3*x2/4 - x3/2 + 1/4, x2, x3)]\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "import sympy as sp\n",
    "x1, x2, x3 = sp.symbols('x1 x2 x3')\n",
    "equation = sp.Eq(4*x1 + 3*x2 + 2*x3, 1)\n",
    "solution = sp.solve(equation, (x1, x2, x3))\n",
    "\n",
    "print(\"Result: \")\n",
    "print(solution)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ca47f0c8-8700-4182-bf80-b147c119071b",
   "metadata": {},
   "source": [
    "<br>\n",
    "c) $3x - 6y = 0$"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "02584d5e-c15e-44a8-bd12-80826d8d8345",
   "metadata": {},
   "source": [
    "Manual Solution:\n",
    "$\n",
    "3x - 6y = 0 \\\\\n",
    "\\frac{3x}{3} = \\frac{6y}{3} \\\\\n",
    "\\boxed{x = 2y}\n",
    "$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "830e91e2-c448-4771-9441-e9a961face70",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result: \n",
      "[(2*y, y)]\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "import sympy as sp\n",
    "x, y = sp.symbols('x y')\n",
    "equation = sp.Eq(3*x - 6*y, 0)\n",
    "solution = sp.solve(equation, (x, y))\n",
    "\n",
    "print(\"Result: \")\n",
    "print(solution)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d0c4f212-6513-4d40-8883-e9fcdf8500cb",
   "metadata": {},
   "source": [
    "<br> 3. Solve the following systems of linear equations <br>\n",
    "a) $ L_1: x - y = 0 \\\\\n",
    "L_2: 2x + y = 3\n",
    "$"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2de93109-cb4d-4c4a-abbc-1682cbc618a9",
   "metadata": {},
   "source": [
    "Manual Solution:\n",
    "$\n",
    "Forward Elimination: \\\\\n",
    "-2(x - y = 0) \\\\\n",
    "-2x + 2y = 0 \\space + \\space2x + y = 3\n",
    "\\\\ = \\frac{3y}{3} = \\frac{3}{3} \\\\\n",
    "\\boxed{y = 1} \\\\\n",
    "$\n",
    "\n",
    "\n",
    "$Backward Substitution: \n",
    "\\\\\n",
    "x - (1) = 0 \\\\\n",
    "\\boxed{x = 1}\n",
    "$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "7c620477-5d8b-4539-b021-77b0db91327a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Solution vector x & y:\n",
      "[1. 1.]\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "A = np.array([[1, -1],\n",
    "              [2, 1]])\n",
    "\n",
    "# coefficients\n",
    "b = np.array([0, 3])\n",
    "\n",
    "# Perform forward elimination to transform A into upper triangular form U\n",
    "# Step 1: Row 2 = Row 2 - 2 * Row 1\n",
    "A = RowAdd(A, 0, 1, -2)\n",
    "\n",
    "# Now, A is in upper triangular form, and we can use BackwardSubstitution to find the solution\n",
    "solution = BackwardSubstitution(A, b)\n",
    "\n",
    "# Print the solution\n",
    "print(\"Solution vector x & y:\")\n",
    "print(solution)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4ac43e56-3f7a-44fb-b1c2-e1855bb6513c",
   "metadata": {},
   "source": [
    "b) $ L_1: x + 5y = -1 \\\\\n",
    "L_2: -x + y = -5 \\\\\n",
    "L_3: 2x + 4y = 4\n",
    "$"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bec126cc-ebf7-4f77-921d-3bf913323429",
   "metadata": {},
   "source": [
    "Manual Solution: <br><br>\n",
    "$\n",
    "\\begin{pmatrix}\n",
    "    1 & 5 &\\bigm| & -1 \\\\\n",
    "    -1 & 1 &\\bigm| & -5 \\\\\n",
    "    2 & 4 &\\bigm| & 4 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} + \\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 5 &\\bigm| & -1 \\\\\n",
    "    0 & 6 &\\bigm| & -6 \\\\\n",
    "    2 & 4 &\\bigm| & 4 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} - 2\\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 5 &\\bigm| & -1 \\\\\n",
    "    0 & 6 &\\bigm| & -6 \\\\\n",
    "    0 & -6 &\\bigm| & 6 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\frac{1}{6}\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 5 &\\bigm| & -1 \\\\\n",
    "    0 & 1 &\\bigm| & -1 \\\\\n",
    "    0 & -6 &\\bigm| & 6 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{1} - 5\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 0 &\\bigm| & 4 \\\\\n",
    "    0 & 1 &\\bigm| & -1 \\\\\n",
    "    0 & -6 &\\bigm| & 6 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} + 6\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 0 &\\bigm| & 4 \\\\\n",
    "    0 & 1 &\\bigm| & -1 \\\\\n",
    "    0 & 0 &\\bigm| & 0 \\\\\n",
    "\\end{pmatrix}\n",
    "$\n",
    "<br><br>\n",
    "Backward Substitution:<br>\n",
    "$x = 4 + 0t$<br>\n",
    "$y = -1 + 0t$ <br>\n",
    "i.e. x = 4 & y = -1\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "63f6a194-8f49-4c1f-8b6d-015fe8123fef",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A (Original)\n",
      "[[ 1  5 -1]\n",
      " [-1  1 -5]\n",
      " [ 2  4  4]] \n",
      "\n",
      "A1\n",
      "[[ 1.  5. -1.]\n",
      " [ 0.  6. -6.]\n",
      " [ 2.  4.  4.]] \n",
      "\n",
      "A2\n",
      "[[ 1.  5. -1.]\n",
      " [ 0.  6. -6.]\n",
      " [ 0. -6.  6.]] \n",
      "\n",
      "A3\n",
      "[[ 1.  5. -1.]\n",
      " [ 0.  1. -1.]\n",
      " [ 0. -6.  6.]] \n",
      "\n",
      "A4\n",
      "[[ 1.  0.  4.]\n",
      " [ 0.  1. -1.]\n",
      " [ 0. -6.  6.]] \n",
      "\n",
      "A5\n",
      "[[ 1.  0.  4.]\n",
      " [ 0.  1. -1.]\n",
      " [ 0.  0.  0.]] \n",
      "\n",
      "Solution to vector x, y & z:\n",
      "[ 4. -1.  0.]\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "A = np.array([[1, 5, -1],\n",
    "              [-1, 1, -5],\n",
    "              [2, 4, 4]])\n",
    "\n",
    "print(\"A (Original)\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 1, 1)\n",
    "print(\"A1\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 2, -2)\n",
    "print(\"A2\")\n",
    "print(A,'\\n')\n",
    "A = RowScale(A, 1, 1/6)\n",
    "print(\"A3\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 1, 0, -5)\n",
    "print(\"A4\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 1, 2, 6)\n",
    "print(\"A5\")\n",
    "print(A,'\\n')\n",
    "\n",
    "last_entries = [] #to get the coefficient array for b\n",
    "\n",
    "for row in A:\n",
    "    last_entry = row[-1]\n",
    "    last_entries.append(last_entry)\n",
    "\n",
    "b = np.array(last_entries)\n",
    "\n",
    "solution = BackwardSubstitution(A, b)\n",
    "\n",
    "print(\"Solution to vector x, y & z:\")\n",
    "print(solution)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fbb483dd-44c7-4606-a035-80d8975f7f9b",
   "metadata": {},
   "source": [
    "<br>\n",
    "c) $ L_1: 2x_1 + 3x_2 -x_3 = -1 \\\\\n",
    "L_2: x_1 + x_3 = 0 \\\\\n",
    "L_3: -x_1 + 2x_2 - 2x_3 = 0\n",
    "$"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "52735fe3-1da5-41b9-b525-8345ed995611",
   "metadata": {},
   "source": [
    "Manual Solution: <br><br>\n",
    "$\n",
    "\\begin{pmatrix}\n",
    "    2 & 3 & -1 &\\bigm| & -1 \\\\\n",
    "    1 & 0 & 1 &\\bigm| & 0 \\\\\n",
    "    -1 & 2 & -2 &\\bigm| & 0 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\frac{1}{2}\\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & \\frac{3}{2} & \\frac{-1}{2} &\\bigm| & \\frac{-1}{2} \\\\\n",
    "    1 & 0 & 1 &\\bigm| & 0 \\\\\n",
    "    -1 & 2 & -2 &\\bigm| & 0 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} - \\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & \\frac{3}{2} & \\frac{-1}{2} &\\bigm| & \\frac{-1}{2} \\\\\n",
    "    0 & \\frac{-3}{2} & \\frac{3}{2} &\\bigm| & \\frac{1}{2} \\\\\n",
    "    -1 & 2 & -2 &\\bigm| & 0 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} + \\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & \\frac{3}{2} & \\frac{-1}{2} &\\bigm| & \\frac{-1}{2} \\\\\n",
    "    0 & \\frac{-3}{2} & \\frac{3}{2} &\\bigm| & \\frac{1}{2} \\\\\n",
    "    0 & \\frac{7}{2} & \\frac{-5}{2} &\\bigm| & \\frac{-1}{2} \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\frac{-2}{3}\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & \\frac{3}{2} & \\frac{-1}{2} &\\bigm| & \\frac{-1}{2} \\\\\n",
    "    0 & 1 & -1 &\\bigm| & \\frac{-1}{3} \\\\\n",
    "    0 & \\frac{7}{2} & \\frac{-5}{2} &\\bigm| & \\frac{-1}{2} \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} - \\frac{7}{2}\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & \\frac{3}{2} & \\frac{-1}{2} &\\bigm| & \\frac{-1}{2} \\\\\n",
    "    0 & 1 & -1 &\\bigm| & \\frac{-1}{3} \\\\\n",
    "    0 & 0 & 1 &\\bigm| & \\frac{-5}{9} \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{1} - \\frac{3}{2}\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 0 & \\frac{1}{3} &\\bigm| & \\frac{1}{3} \\\\\n",
    "    0 & 1 & -1 &\\bigm| & \\frac{-1}{3} \\\\\n",
    "    0 & 0 & 1 &\\bigm| & \\frac{-5}{9} \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{1} - \\frac{1}{3}\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 0 & 0 &\\bigm| & 0 \\\\\n",
    "    0 & 1 & -1 &\\bigm| & \\frac{-1}{3} \\\\\n",
    "    0 & 0 & 1 &\\bigm| & \\frac{-5}{9} \\\\\n",
    "\\end{pmatrix}\n",
    "$\n",
    "\n",
    "<br><br>\n",
    "Backward Substitution:<br>\n",
    "$\\boxed{x_1 = 0}$<br>\n",
    "$\\boxed{x_3 = -\\frac{5}{9}}$ <br>\n",
    "$x_2 - x_3 = -\\frac{1}{3}$<br>\n",
    "$x_2 - (-\\frac{5}{9}) = -\\frac{1}{3}$<br>\n",
    "$x_2 = -\\frac{1}{3} - \\frac{5}{9}$<br>\n",
    "$\\boxed{x_2 = -\\frac{8}{9}}$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "9ceb4cd5-2f81-4756-ba51-e71ac5692f67",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A (Original)\n",
      "[[ 2  3 -1 -1]\n",
      " [ 1  0  1  0]\n",
      " [-1  2 -2  0]] \n",
      "\n",
      "A1\n",
      "[[ 1.   1.5 -0.5 -0.5]\n",
      " [ 1.   0.   1.   0. ]\n",
      " [-1.   2.  -2.   0. ]] \n",
      "\n",
      "A2\n",
      "[[ 1.   1.5 -0.5 -0.5]\n",
      " [ 0.  -1.5  1.5  0.5]\n",
      " [-1.   2.  -2.   0. ]] \n",
      "\n",
      "A3\n",
      "[[ 1.   1.5 -0.5 -0.5]\n",
      " [ 0.  -1.5  1.5  0.5]\n",
      " [ 0.   3.5 -2.5 -0.5]] \n",
      "\n",
      "A4\n",
      "[[ 1.          1.5        -0.5        -0.5       ]\n",
      " [-0.          1.         -1.         -0.33333333]\n",
      " [ 0.          3.5        -2.5        -0.5       ]] \n",
      "\n",
      "A5\n",
      "[[ 1.          1.5        -0.5        -0.5       ]\n",
      " [-0.          1.         -1.         -0.33333333]\n",
      " [ 0.          0.          1.          0.66666667]] \n",
      "\n",
      "A6\n",
      "[[ 1.          0.          1.          0.        ]\n",
      " [-0.          1.         -1.         -0.33333333]\n",
      " [ 0.          0.          1.          0.66666667]] \n",
      "\n",
      "A7\n",
      "[[ 1.          0.5         0.5        -0.16666667]\n",
      " [-0.          1.         -1.         -0.33333333]\n",
      " [ 0.          0.          1.          0.66666667]] \n",
      "\n",
      "Solution to vector x_1, x_2 & x_3:\n",
      "[-0.66666667  0.33333333  0.66666667]\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "A = np.array([[2, 3, -1, -1],\n",
    "              [1, 0, 1, 0],\n",
    "              [-1, 2, -2, 0]])\n",
    "\n",
    "print(\"A (Original)\")\n",
    "print(A,'\\n')\n",
    "A = RowScale(A, 0, 1/2)\n",
    "print(\"A1\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 1, -1)\n",
    "print(\"A2\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 2, 1)\n",
    "print(\"A3\")\n",
    "print(A,'\\n')\n",
    "A = RowScale(A, 1, -2/3)\n",
    "print(\"A4\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 1, 2, -7/2)\n",
    "print(\"A5\")\n",
    "print(A,'\\n')\n",
    "\n",
    "A = RowAdd(A, 1, 0, -3/2) #smth is wrong here jusko\n",
    "print(\"A6\")\n",
    "print(A,'\\n')\n",
    "\n",
    "A = RowAdd(A, 1, 0, 1/2)\n",
    "print(\"A7\")\n",
    "print(A,'\\n')\n",
    "\n",
    "\n",
    "last_entries = [] #to get the coefficient array for b\n",
    "\n",
    "for row in A:\n",
    "    last_entry = row[-1]\n",
    "    last_entries.append(last_entry)\n",
    "\n",
    "b = np.array(last_entries)\n",
    "\n",
    "solution = BackwardSubstitution(A, b)\n",
    "\n",
    "print(\"Solution to vector x_1, x_2 & x_3:\")\n",
    "print(solution)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "15b99188-e359-4d99-805b-6420b70bfec1",
   "metadata": {},
   "source": [
    "<br><br>\n",
    "4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.<br>\n",
    "a. <br>\n",
    "\\begin{pmatrix}\n",
    "   1 & 0 & 1 \\\\\n",
    "   0 & 0 & 3 \\\\\n",
    "   0 & 1 & 0 \\\\\n",
    "\\end{pmatrix}<br><br>\n",
    "- This matrix is not in row echelon form since the leading entry in Row 2 is greater than the bottom-right entry of Row 1. Moreover, it does not meet the requirements for reduced row echelon form (RREF) as it first needs to be in row echelon form. Additionally, the leading entries are not the only non-zero entries in their respective columns.\n",
    "<br>\n",
    "\n",
    "b. <br>\n",
    "\\begin{pmatrix}\n",
    "   7 & 0 & 1 & 0 \\\\\n",
    "   0 & 1 & -1 & 4 \\\\\n",
    "   0 & 0 & 0 & 0 \\\\\n",
    "\\end{pmatrix}<br><br>\n",
    "- It meets the criteria for row echelon form (REF) since the leading entries for Rows 1 and 2 are appropriately positioned, and below the leading entry in Row 1 consists of zeros. However, it does not qualify as reduced row echelon form (RREF) due to the leading entry in Row 1 not being 1. <br>\n",
    "\n",
    "c. <br>\n",
    "\\begin{pmatrix}\n",
    "   0 & 1 & 3 & 0 \\\\\n",
    "   0 & 0 & 0 & 1 \\\\\n",
    "\\end{pmatrix}<br><br>\n",
    "- This matrix is in reduced row echelon form (RREF) as the bottom row contains the most zeros, and each row has a leading entry of 1.<br>\n",
    "\n",
    "d. <br>\n",
    "\\begin{pmatrix}\n",
    "   0 & 0 & 0 \\\\\n",
    "   0 & 0 & 0 \\\\\n",
    "   0 & 0 & 0 \\\\\n",
    "\\end{pmatrix}<br><br>\n",
    "- It neither qualifies as row echelon form (REF) nor reduced row echelon form (RREF) as all entries are zeroes, making it a Zero/Null Matrix.<br>\n",
    "\n",
    "e. <br>\n",
    "\\begin{pmatrix}\n",
    "   1 & 0 & 3 & -4 & 0 \\\\\n",
    "   0 & 0 & 0 & 0 & 0 \\\\\n",
    "   0 & 1 & 5 & 0 & 1 \\\\\n",
    "\\end{pmatrix}<br><br>\n",
    "- Not in row echelon form (REF) as the row with the most zeros is found in Row 2, not at the bottom. Therefore, it does not qualify as reduced row echelon form (RREF) as it first needs to satisfy the conditions for row echelon form.<br>\n",
    "\n",
    "f. <br>\n",
    "\\begin{pmatrix}\n",
    "   0 & 0 & 1 \\\\\n",
    "   0 & 1 & 0 \\\\\n",
    "   1 & 0 & 0 \\\\\n",
    "\\end{pmatrix}<br><br>\n",
    "- This matrix is in reduced row echelon form (RREF) as it comprises leading entries of 1, surrounded by zeros.<br>\n",
    "\n",
    "g. <br>\n",
    "\\begin{pmatrix}\n",
    "   1 & 2 & 3 \\\\\n",
    "   1 & 0 & 0 \\\\\n",
    "   0 & 1 & 1 \\\\\n",
    "   0 & 0 & 1 \\\\\n",
    "\\end{pmatrix}<br><br>\n",
    "- It fulfills the criteria for row echelon form (REF) as non-zero entries are located below each leading entry. Additionally, the entries in Rows 3 to 4 are appropriately positioned.<br>\n",
    "\n",
    "h. <br>\n",
    "\\begin{pmatrix}\n",
    "   2 & 1 & 3 & 5 \\\\\n",
    "   0 & 0 & 1 & -1 \\\\\n",
    "   0 & 0 & 0 & 3 \\\\\n",
    "   0 & 0 & 0 & 0 \\\\\n",
    "\\end{pmatrix}<br><br>\n",
    "- This matrix satisfies the rule for row echelon form (REF) as the row with the most zeros is positioned at the bottom. Moreover, zeros are present below each leading entry.<br><br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9d072c82-8ab2-4ba9-b2ba-f260b2075b16",
   "metadata": {},
   "source": [
    "5. Solve the following systems of linear equations<br>\n",
    "a.<br> \n",
    "\\begin{equation}\n",
    "x_1+2x_2-3x_3=9 \\\\\n",
    "2x_1-x_2-x_3=0 \\\\\n",
    "4x_1-x_2+x_3=4 \\\\\n",
    "\\end{equation}\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "59517282-bd6c-48f0-b587-5c19384ab88e",
   "metadata": {},
   "source": [
    "Manual Solution:<br><br>\n",
    "$\n",
    "\\begin{pmatrix}\n",
    "    1 & 2 & -3 &\\bigm| & 9 \\\\\n",
    "    2 & -1 & -1 &\\bigm| & 0 \\\\\n",
    "    4 & -1 & 1 &\\bigm| & 4 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} - 2\\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 2 & -3 &\\bigm| & 9 \\\\\n",
    "    0 & -5 & 5 &\\bigm| & -18 \\\\\n",
    "    4 & -1 & 1 &\\bigm| & 4 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} - 4\\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 2 & -3 &\\bigm| & 9 \\\\\n",
    "    0 & -5 & 5 &\\bigm| & -18 \\\\\n",
    "    0 & -9 & 13 &\\bigm| & -32 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{-\\frac{1}{5}\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 2 & -3 &\\bigm| & 9 \\\\\n",
    "    0 & 1 & -1 &\\bigm| & \\frac{18}{5} \\\\\n",
    "    0 & -9 & 13 &\\bigm| & -32 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} - 9\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 2 & -3 &\\bigm| & 9 \\\\\n",
    "    0 & 1 & -1 &\\bigm| & \\frac{18}{5} \\\\\n",
    "    0 & 0 & 4 &\\bigm| & -\\frac{2}{5} \\\\\n",
    "\\end{pmatrix} \\\\\n",
    "\\\\\n",
    "New Equations:\\\\\n",
    "= x_1 + 2x_2 - 3x_3 = 9\\\\\n",
    "= x_2 - (-x_3) = \\frac{18}{5}\\\\\n",
    "= 4x_3 = -\\frac{2}{5}\\\\\n",
    "\\\\\n",
    "Backwards Substitution: \\\\\n",
    "\\frac{4x_3}{4} = \\frac{\\frac{2}{5}}{4}\\\\\n",
    "\\boxed{x_3 = \\frac{1}{10}}\\\\\n",
    "\\\\\n",
    "x_2 - (-x_3) = \\frac{18}{5}\\\\\n",
    "x_2 - (\\frac{1}{10}) = \\frac{18}{5}\\\\\n",
    "x_2 = \\frac{18}{5} + \\frac{1}{10}\\\\\n",
    "\\boxed{x_2 = \\frac{37}{10}}\\\\\n",
    "x_1 + 2x_2 - 3x_3 = 9\\\\\n",
    "x_1 + 2(\\frac{37}{10}) - 3(\\frac{1}{10}) = 9\\\\\n",
    "x_1 + \\frac{37}{5}) - \\frac{3}{10} = 9\\\\\n",
    "\\boxed{x_1 = \\frac{19}{10}}\\\\\n",
    "$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "9b956911-d25a-44e7-8dde-7a6e0c1aaa91",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A (Original)\n",
      "[[ 1  2 -3  9]\n",
      " [ 2 -1 -1  0]\n",
      " [ 4 -1  1  4]] \n",
      "\n",
      "A1\n",
      "[[  1.   2.  -3.   9.]\n",
      " [  0.  -5.   5. -18.]\n",
      " [  4.  -1.   1.   4.]] \n",
      "\n",
      "A2\n",
      "[[  1.   2.  -3.   9.]\n",
      " [  0.  -5.   5. -18.]\n",
      " [  0.  -9.  13. -32.]] \n",
      "\n",
      "A3\n",
      "[[  1.    2.   -3.    9. ]\n",
      " [ -0.    1.   -1.    3.6]\n",
      " [  0.   -9.   13.  -32. ]] \n",
      "\n",
      "A4\n",
      "[[ 1.   2.  -3.   9. ]\n",
      " [-0.   1.  -1.   3.6]\n",
      " [ 0.   0.   4.   0.4]] \n",
      "\n",
      "Solution to vectors x1, x2 & x3:\n",
      "[1.9 3.7 0.1]\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "A = np.array([[1, 2, -3, 9],\n",
    "              [2, -1, -1, 0],\n",
    "              [4, -1, 1, 4]])\n",
    "\n",
    "print(\"A (Original)\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 1, -2)\n",
    "print(\"A1\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 2, -4)\n",
    "print(\"A2\")\n",
    "print(A,'\\n')\n",
    "A = RowScale(A, 1, -1/5)\n",
    "print(\"A3\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 1, 2, 9)\n",
    "print(\"A4\")\n",
    "print(A,'\\n')\n",
    "\n",
    "\n",
    "last_entries = [] #to get the coefficient array for b\n",
    "\n",
    "for row in A:\n",
    "    last_entry = row[-1]\n",
    "    last_entries.append(last_entry)\n",
    "\n",
    "b = np.array(last_entries)\n",
    "\n",
    "solution = BackwardSubstitution(A, b)\n",
    "\n",
    "print(\"Solution to vectors x1, x2 & x3:\")\n",
    "print(solution)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ae6a8835-6a06-4c93-972d-7c69a8dd74e9",
   "metadata": {},
   "source": [
    "<br>b. <br>\n",
    "\\begin{equation}\n",
    "x+2y= -1 \\\\\n",
    "2x+y+z = 1 \\\\\n",
    "-x+y-z = -1\n",
    "\\end{equation}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "42f45ef3-3806-46c6-8f22-7f8bf30a32b3",
   "metadata": {},
   "source": [
    "Manual Solution:<br><br>\n",
    "$\n",
    "\\begin{pmatrix}\n",
    "    1 & 2 & 0 &\\bigm| & -1 \\\\\n",
    "    2 & 1 & 1 &\\bigm| & 1 \\\\\n",
    "    -1 & 1 & -1 &\\bigm| & -1 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} - 2\\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 2 & 0 &\\bigm| & -1 \\\\\n",
    "    0 & -3 & 1 &\\bigm| & 3 \\\\\n",
    "    -1 & 1 & -1 &\\bigm| & -1 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} + \\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 2 & 0 &\\bigm| & -1 \\\\\n",
    "    0 & -3 & 1 &\\bigm| & 3 \\\\\n",
    "    0 & 3 & -1 &\\bigm| & -2 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} + \\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 2 & 0 &\\bigm| & -1 \\\\\n",
    "    0 & -3 & 1 &\\bigm| & 3 \\\\\n",
    "    0 & 0 & 0 &\\bigm| & 1 \\\\\n",
    "\\end{pmatrix}\n",
    "$\n",
    "<br><br>\n",
    "- L3: 0z = there is no solution to this due to 1 being not possible."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "007735c5-a70a-4dea-b5f3-f595e51770a8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A (Original)\n",
      "[[ 1  2  0 -1]\n",
      " [ 2  1  1  1]\n",
      " [-1  1 -1 -1]] \n",
      "\n",
      "A1\n",
      "[[ 1.  2.  0. -1.]\n",
      " [ 0. -3.  1.  3.]\n",
      " [-1.  1. -1. -1.]] \n",
      "\n",
      "A2\n",
      "[[ 1.  2.  0. -1.]\n",
      " [ 0. -3.  1.  3.]\n",
      " [ 0.  3. -1. -2.]] \n",
      "\n",
      "A3\n",
      "[[ 1.  2.  0. -1.]\n",
      " [ 0. -3.  1.  3.]\n",
      " [ 0.  0.  0.  1.]] \n",
      "\n",
      "Solution to vectors x, y & z:\n",
      "[ 1. -1.  0.]\n",
      "Not possible since 0x + 0y + 0z != 1\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "A = np.array([[1, 2, 0, -1],\n",
    "              [2, 1, 1, 1],\n",
    "              [-1, 1, -1, -1]])\n",
    "\n",
    "print(\"A (Original)\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 1, -2)\n",
    "print(\"A1\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 2, 1)\n",
    "print(\"A2\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 1, 2, 1)\n",
    "print(\"A3\")\n",
    "print(A,'\\n')\n",
    "\n",
    "\n",
    "last_entries = [] #to get the coefficient array for b\n",
    "\n",
    "for row in A:\n",
    "    last_entry = row[-1]\n",
    "    last_entries.append(last_entry)\n",
    "\n",
    "b = np.array(last_entries)\n",
    "\n",
    "solution = BackwardSubstitution(A, b)\n",
    "\n",
    "print(\"Solution to vectors x, y & z:\")\n",
    "print(solution)\n",
    "print(\"Not possible since 0x + 0y + 0z != 1\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4b9194d0-a036-423f-931a-04ddc853c4c2",
   "metadata": {},
   "source": [
    "c. <br>\n",
    "\\begin{equation}\n",
    "x_1-3x_2-2x_3=0 \\\\\n",
    "-x_1+2x_2+x_3=0 \\\\\n",
    "2x_1+4x_2+6x_3=0 \\\\\n",
    "\\end{equation}\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "85c51bc4-d6a2-487d-90a8-182e5c5a20a1",
   "metadata": {},
   "source": [
    "Manual Solution:<br><br>\n",
    "$\n",
    "\\begin{pmatrix}\n",
    "    1 & -3 & -2 &\\bigm| & 0 \\\\\n",
    "    -1 & 2 & 1 &\\bigm| & 0 \\\\\n",
    "    2 & 4 & 6 &\\bigm| & 0 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} + \\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & -3 & -2 &\\bigm| & 0 \\\\\n",
    "    0 & -1 & -1 &\\bigm| & 0 \\\\\n",
    "    2 & 4 & 6 &\\bigm| & 0 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} - 2\\text{R}_{1}}\n",
    "\\begin{pmatrix}\n",
    "    1 & -3 & -2 &\\bigm| & 0 \\\\\n",
    "    0 & -1 & -1 &\\bigm| & 0 \\\\\n",
    "    0 & 10 & 10 &\\bigm| & 0 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} + 10\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & -3 & -2 &\\bigm| & 0 \\\\\n",
    "    0 & -1 & -1 &\\bigm| & 0 \\\\\n",
    "    0 & 0 & 0 &\\bigm| & 0 \\\\\n",
    "\\end{pmatrix}\n",
    "\\xrightarrow{\\text{R}_{1} - 3\\text{R}_{2}}\n",
    "\\begin{pmatrix}\n",
    "    1 & 0 & 1 &\\bigm| & 0 \\\\\n",
    "    0 & 1 & 1 &\\bigm| & 0 \\\\\n",
    "    0 & 0 & 0 &\\bigm| & 0 \\\\\n",
    "\\end{pmatrix}\n",
    "$\n",
    "<br><br>\n",
    "- L3: 0x1 + 0x2 + 0x3 = 0, x3 can have any value.<br>\n",
    "L2: x2 + x3 = 0 = x2 = -x3<br>\n",
    "L1: x1 + x3 = 0 = x1 + -x3<br>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "7ce187e6-0a8f-45b3-9b71-73a3f75bea89",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A (Original)\n",
      "[[ 1 -3 -2  0]\n",
      " [-1  2  1  0]\n",
      " [ 2  4  6  0]] \n",
      "\n",
      "A1\n",
      "[[ 1. -3. -2.  0.]\n",
      " [ 0. -1. -1.  0.]\n",
      " [ 2.  4.  6.  0.]] \n",
      "\n",
      "A2\n",
      "[[ 1. -3. -2.  0.]\n",
      " [ 0. -1. -1.  0.]\n",
      " [ 0. 10. 10.  0.]] \n",
      "\n",
      "A3\n",
      "[[ 1. -3. -2.  0.]\n",
      " [ 0. -1. -1.  0.]\n",
      " [ 0.  0.  0.  0.]] \n",
      "\n",
      "A4\n",
      "[[ 1.  0.  1.  0.]\n",
      " [ 0. -1. -1.  0.]\n",
      " [ 0.  0.  0.  0.]] \n",
      "\n",
      "Solution to vectors x1, x2 & x3:\n",
      "[ 0. -0.  0.]\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "A = np.array([[1, -3, -2, 0],\n",
    "              [-1, 2, 1, 0],\n",
    "              [2, 4, 6, 0]])\n",
    "\n",
    "print(\"A (Original)\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 1, 1)\n",
    "print(\"A1\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 2, -2)\n",
    "print(\"A2\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 1, 2, 10)\n",
    "print(\"A3\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 1, 0, -3)\n",
    "print(\"A4\")\n",
    "print(A,'\\n')\n",
    "\n",
    "\n",
    "last_entries = [] #to get the coefficient array for b\n",
    "\n",
    "for row in A:\n",
    "    last_entry = row[-1]\n",
    "    last_entries.append(last_entry)\n",
    "\n",
    "b = np.array(last_entries)\n",
    "\n",
    "solution = BackwardSubstitution(A, b)\n",
    "\n",
    "print(\"Solution to vectors x1, x2 & x3:\")\n",
    "print(solution)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "df901f40-7d70-4c70-9c68-c920b58e6dfe",
   "metadata": {},
   "source": [
    "<br>d. <br>\n",
    "\\begin{equation}\n",
    "w+x+2y+z=1 \\\\\n",
    "w-x-y+z=0 \\\\\n",
    "x+y=1 \\\\\n",
    "w+x+z=2\n",
    "\\end{equation}\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0bbc2686-09c4-4a41-aa3c-398262c9715c",
   "metadata": {},
   "source": [
    "Manual Solution:<br><br>\n",
    "$\n",
    "\\begin{align*}\n",
    "w + x + 2y + z &= 1 \\\\\n",
    "w - x - y + z &= 0 \\\\\n",
    "x + y &= 1 \\\\\n",
    "w + x + z &= 2\n",
    "\\end{align*}\\\\\n",
    "$\n",
    "<br><br>\n",
    "$\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 2 & 1 & \\big| & 1 \\\\\n",
    "1 & -1 & -1 & 1 & \\big| & 0 \\\\\n",
    "0 & 1 & 1 & 0 & \\big| & 1 \\\\\n",
    "1 & 1 & 0 & 1 & \\big| & 2 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} - \\text{R}_{1}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 2 & 1 & \\big| & 1 \\\\\n",
    "0 & -2 & -3 & 0 & \\big| & -1 \\\\\n",
    "0 & 1 & 1 & 0 & \\big| & 1 \\\\\n",
    "1 & 1 & 0 & 1 & \\big| & 2 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} + 2\\text{R}_{2}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 2 & 1 & \\big| & 1 \\\\\n",
    "0 & -2 & -3 & 0 & \\big| & -1 \\\\\n",
    "0 & 0 & 1 & 0 & \\big| & 1 \\\\\n",
    "1 & 1 & 0 & 1 & \\big| & 2 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{4} + \\text{R}_{3}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 2 & 1 & \\big| & 1 \\\\\n",
    "0 & -2 & -3 & 0 & \\big| & -1 \\\\\n",
    "0 & 0 & 1 & 0 & \\big| & 1 \\\\\n",
    "1 & 1 & -1 & 1 & \\big| & 3 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{-1\\text{R}_{3}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 2 & 1 & \\big| & 1 \\\\\n",
    "0 & -2 & -3 & 0 & \\big| & -1 \\\\\n",
    "0 & 0 & -1 & 0 & \\big| & -1 \\\\\n",
    "1 & 1 & -1 & 1 & \\big| & 3 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} - 2\\text{R}_{3}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 2 & 1 & \\big| & 1 \\\\\n",
    "0 & -2 & 1 & 0 & \\big| & 1 \\\\\n",
    "0 & 0 & -1 & 0 & \\big| & -1 \\\\\n",
    "1 & 1 & -1 & 1 & \\big| & 3 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{1} - \\text{R}_{3}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 2 & 1 & \\big| & 2 \\\\\n",
    "0 & -2 & 1 & 0 & \\big| & 1 \\\\\n",
    "0 & 0 & -1 & 0 & \\big| & -1 \\\\\n",
    "1 & 1 & -1 & 1 & \\big| & 3 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{4} - \\text{R}_{3}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 2 & 1 & \\big| & 2 \\\\\n",
    "0 & -2 & 1 & 0 & \\big| & 1 \\\\\n",
    "0 & 0 & -1 & 0 & \\big| & -1 \\\\\n",
    "1 & 1 & 0 & 1 & \\big| & 4 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{1} - 2\\text{R}_{3}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 0 & 1 & \\big| & 4 \\\\\n",
    "0 & -2 & 1 & 0 & \\big| & 1 \\\\\n",
    "0 & 0 & -1 & 0 & \\big| & -1 \\\\\n",
    "1 & 1 & 0 & 1 & \\big| & 4 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{-\\frac{1}{2}\\text{R}_{2}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 0 & 1 & \\big| & 4 \\\\\n",
    "0 & 1 & -\\frac{1}{2} & 0 & \\big| & -\\frac{1}{2} \\\\\n",
    "0 & 0 & -1 & 0 & \\big| & -1 \\\\\n",
    "1 & 1 & 0 & 1 & \\big| & 4 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{1} - \\text{R}_{2}}\n",
    "\\begin{bmatrix}\n",
    "1 & 0 & \\frac{1}{2} & 1 & \\big| & \\frac{9}{2} \\\\\n",
    "0 & 1 & -\\frac{1}{2} & 0 & \\big| & -\\frac{1}{2} \\\\\n",
    "0 & 0 & -1 & 0 & \\big| & -1 \\\\\n",
    "1 & 1 & 0 & 1 & \\big| & 4 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{4} - \\text{R}_{1}}\n",
    "\\begin{bmatrix}\n",
    "1 & 0 & \\frac{1}{2} & 1 & \\big| & \\frac{9}{2} \\\\\n",
    "0 & 1 & -\\frac{1}{2} & 0 & \\big| & -\\frac{1}{2} \\\\\n",
    "0 & 0 & -1 & 0 & \\big| & -1 \\\\\n",
    "0 & 0 & 1 & 1 & \\big| & 4 \\\\\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{1} - \\text{R}_{4}}\n",
    "\\begin{bmatrix}\n",
    "1 & 0 & 0 & 0 & \\big| & 0 \\\\\n",
    "0 & 1 & 0 & 0 & \\big| & -\\frac{1}{2} \\\\\n",
    "0 & 0 & -1 & 0 & \\big| & -1 \\\\\n",
    "0 & 0 & 1 & 1 & \\big| & 4 \\\\\n",
    "\\end{bmatrix}\n",
    "$\n",
    "\n",
    "\\begin{align*}\n",
    "w &= 0 \\\\\n",
    "x &= -\\frac{1}{2} \\\\\n",
    "y &= -1 \\\\\n",
    "z &= 0 \\\\\n",
    "\\end{align*}\n",
    "<br>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "id": "fdba2f27-47b2-4cad-8969-cf715848a308",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A (Original)\n",
      "[[ 1  1  2  1  1]\n",
      " [ 1 -1 -1  1  0]\n",
      " [ 0  1  1  0  1]\n",
      " [ 1  1  0  1  2]] \n",
      "\n",
      "A1\n",
      "[[ 1.  1.  2.  1.  1.]\n",
      " [ 0. -2. -3.  0. -1.]\n",
      " [ 0.  1.  1.  0.  1.]\n",
      " [ 1.  1.  0.  1.  2.]] \n",
      "\n",
      "A2\n",
      "[[ 1.  1.  2.  1.  1.]\n",
      " [ 0. -2. -3.  0. -1.]\n",
      " [ 0. -3. -5.  0. -1.]\n",
      " [ 1.  1.  0.  1.  2.]] \n",
      "\n",
      "A3\n",
      "[[ 1.  1.  2.  1.  1.]\n",
      " [ 0. -2. -3.  0. -1.]\n",
      " [ 0. -3. -5.  0. -1.]\n",
      " [ 1. -2. -5.  1.  1.]] \n",
      "\n",
      "A4\n",
      "[[ 1.  1.  2.  1.  1.]\n",
      " [ 0. -2. -3.  0. -1.]\n",
      " [-0.  3.  5. -0.  1.]\n",
      " [ 1. -2. -5.  1.  1.]] \n",
      "\n",
      "A5\n",
      "[[  1.   1.   2.   1.   1.]\n",
      " [  0.  -8. -13.   0.  -3.]\n",
      " [ -0.   3.   5.  -0.   1.]\n",
      " [  1.  -2.  -5.   1.   1.]] \n",
      "\n",
      "A6\n",
      "[[  1.  -2.  -3.   1.   0.]\n",
      " [  0.  -8. -13.   0.  -3.]\n",
      " [ -0.   3.   5.  -0.   1.]\n",
      " [  1.  -2.  -5.   1.   1.]] \n",
      "\n",
      "A7\n",
      "[[  1.  -2.  -3.   1.   0.]\n",
      " [  0.  -8. -13.   0.  -3.]\n",
      " [ -0.   3.   5.  -0.   1.]\n",
      " [  1.  -5. -10.   1.   0.]] \n",
      "\n",
      "A8\n",
      "[[  1.  -8. -13.   1.  -2.]\n",
      " [  0.  -8. -13.   0.  -3.]\n",
      " [ -0.   3.   5.  -0.   1.]\n",
      " [  1.  -5. -10.   1.   0.]] \n",
      "\n",
      "A9\n",
      "[[  1.   -8.  -13.    1.   -2. ]\n",
      " [ -0.    4.    6.5  -0.    1.5]\n",
      " [ -0.    3.    5.   -0.    1. ]\n",
      " [  1.   -5.  -10.    1.    0. ]] \n",
      "\n",
      "A10\n",
      "[[  1.  -12.  -19.5   1.   -3.5]\n",
      " [ -0.    4.    6.5  -0.    1.5]\n",
      " [ -0.    3.    5.   -0.    1. ]\n",
      " [  1.   -5.  -10.    1.    0. ]] \n",
      "\n",
      "A11\n",
      "[[  1.  -12.  -19.5   1.   -3.5]\n",
      " [ -0.    4.    6.5  -0.    1.5]\n",
      " [ -0.    3.    5.   -0.    1. ]\n",
      " [  0.    7.    9.5   0.    3.5]] \n",
      "\n",
      "A12\n",
      "[[  1.  -19.  -29.    1.   -7. ]\n",
      " [ -0.    4.    6.5  -0.    1.5]\n",
      " [ -0.    3.    5.   -0.    1. ]\n",
      " [  0.    7.    9.5   0.    3.5]] \n",
      "\n",
      "Solution to vectors x, y, z, w:\n",
      "[-0.25  0.05  0.2   0.  ]\n"
     ]
    }
   ],
   "source": [
    "# pythonic solution #\n",
    "A = np.array([[1, 1, 2, 1, 1],\n",
    "              [1, -1, -1, 1, 0],\n",
    "              [0, 1, 1, 0, 1],\n",
    "              [1, 1, 0, 1, 2]])\n",
    "\n",
    "print(\"A (Original)\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 1, -1)\n",
    "print(\"A1\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 1, 2, 2)\n",
    "print(\"A2\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 2, 3, 1)\n",
    "print(\"A3\")\n",
    "print(A,'\\n')\n",
    "A = RowScale(A, 2, -1)\n",
    "print(\"A4\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 2, 1, -2)\n",
    "print(\"A5\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 2, 0, -1)\n",
    "print(\"A6\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 2, 3, -1)\n",
    "print(\"A7\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 2, 0, -2)\n",
    "print(\"A8\")\n",
    "print(A,'\\n')\n",
    "A = RowScale(A, 1, -1/2)\n",
    "print(\"A9\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 1, 0, -1)\n",
    "print(\"A10\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 0, 3, -1)\n",
    "print(\"A11\")\n",
    "print(A,'\\n')\n",
    "A = RowAdd(A, 3, 0, -1)\n",
    "print(\"A12\")\n",
    "print(A,'\\n')\n",
    "\n",
    "\n",
    "last_entries = [] #to get the coefficient array for b\n",
    "\n",
    "for row in A:\n",
    "    last_entry = row[-1]\n",
    "    last_entries.append(last_entry)\n",
    "\n",
    "b = np.array(last_entries)\n",
    "\n",
    "solution = BackwardSubstitution(A, b)\n",
    "\n",
    "print(\"Solution to vectors x, y, z, w:\")\n",
    "print(solution)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6084dcaf-c1dd-446a-b560-0f63dd30fa62",
   "metadata": {},
   "source": [
    "6. Determine if the vectors are linear combinations<br>\n",
    "a. <br>\n",
    " \\begin{equation}\n",
    "    \\textbf{v} = \\begin{bmatrix} 1 \\\\ 2 \\end{bmatrix} \\ \n",
    "    \\textbf{u}_2 = \\begin{bmatrix} -1 \\\\ 3 \\end{bmatrix}\\\n",
    "    \\textbf{u}_3 = \\begin{bmatrix} 2 \\\\ -6 \\end{bmatrix}\\\\\n",
    "\\end{equation}\n",
    "<br>\n",
    "Manual Solution:<br>\n",
    "\\[\n",
    "x \\textbf{u}_2 + y \\textbf{u}_3 = \\textbf{v}\n",
    "\\]\n",
    "\\begin{align*}\n",
    "-x + 2y &= 1 \\\\\n",
    "3x - 6y &= 2\n",
    "\\end{align*}\n",
    "<br>\n",
    "$\n",
    "\\begin{bmatrix}\n",
    "-1 & 2 & | & 1 \\\\\n",
    "3 & -6 & | & 2\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} + 3\\text{R}_{1}}\n",
    "\\begin{bmatrix}\n",
    "-1 & 2 & | & 1 \\\\\n",
    "0 & 0 & | & 5\n",
    "\\end{bmatrix}\n",
    "$\n",
    "\n",
    "- The inconsistency of this system arises from the last row, which suggests an impossibility: 0 cannot equal 5. Consequently, vector v cannot be expressed as a linear combination of u2 and u3.\n",
    "\n",
    "<br><br>\n",
    "\n",
    "b. <br>\n",
    " \\begin{equation}\n",
    "    \\textbf{v} = \\begin{bmatrix} 1 \\\\ 2 \\\\ 3 \\end{bmatrix} \\ \n",
    "    \\textbf{u}_2 = \\begin{bmatrix} 1 \\\\ 1 \\\\ 0 \\end{bmatrix}\\\n",
    "    \\textbf{u}_3 = \\begin{bmatrix} 0 \\\\ 1 \\\\ 1 \\end{bmatrix}\\\\\n",
    "\\end{equation}\n",
    "<br>\n",
    "Manual Solution:\n",
    "\\begin{align*}\n",
    "x + 0 &= 1 \\\\\n",
    "x + y &= 2 \\\\\n",
    "0 + y &= 3\n",
    "\\end{align*}\n",
    "\n",
    "$\n",
    "\\begin{bmatrix}\n",
    "1 & 0 & | & 1 \\\\\n",
    "1 & 1 & | & 2 \\\\\n",
    "0 & 1 & | & 3\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} - \\tb. <br>\n",
    "\\begin{equation}\n",
    "x+2y= -1 \\\\\n",
    "2x+y+z = 1 \\\\\n",
    "-x+y-z = -1\n",
    "\\end{equation}ext{R}_{1}}\n",
    "\\begin{bmatrix}\n",
    "1 & 0 & | & 1 \\\\\n",
    "0 & 1 & | & 1 \\\\\n",
    "0 & 1 & | & 3\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} - \\text{R}_{2}}\n",
    "\\begin{bmatrix}\n",
    "1 & 0 & | & 1 \\\\\n",
    "0 & 1 & | & 1 \\\\\n",
    "0 & 0 & | & 2\n",
    "\\end{bmatrix}\n",
    "$\n",
    "<br>\n",
    "- x = 1 and y = 1. Therefore, the vector is a linear combination of the vectors given vectors.\n",
    "<br><br>\n",
    "c. <br>\n",
    " \\begin{equation}\n",
    "    \\textbf{v} = \\begin{bmatrix} 3 \\\\ 1 \\\\ -2 \\end{bmatrix} \\ \n",
    "    \\textbf{u}_2 = \\begin{bmatrix} 1 \\\\ 1 \\\\ 0 \\end{bmatrix}\\\n",
    "    \\textbf{u}_3 = \\begin{bmatrix} 0 \\\\ 1 \\\\ 1 \\end{bmatrix}\\\\\n",
    "\\end{equation}\n",
    "<br>\n",
    "Manual Solution:\n",
    "\n",
    "\\begin{align*}\n",
    "x + 0 &= 3 \\\\\n",
    "x + y &= 1 \\\\\n",
    "0 + y &= -2\n",
    "\\end{align*}\n",
    "<br>\n",
    "$\n",
    "\\begin{bmatrix}\n",
    "1 & 0 & | & 3 \\\\\n",
    "1 & 1 & | & 1 \\\\\n",
    "0 & 1 & | & -2\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} - \\text{R}_{1}}\n",
    "\\begin{bmatrix}\n",
    "1 & 0 & | & 3 \\\\\n",
    "0 & 1 & | & -2 \\\\\n",
    "0 & 1 & | & -2\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} - \\text{R}_{2}}\n",
    "\\begin{bmatrix}\n",
    "1 & 0 & | & 3 \\\\\n",
    "0 & 1 & | & -2 \\\\\n",
    "0 & 0 & | & 0\n",
    "\\end{bmatrix}\n",
    "$\n",
    "<br>\n",
    "- Now, the system is consistent and has infinitely many solutions. Therefore, vector v is a linear combination of u2 and u3, and there are multiple solutions for x and y.\n",
    "<br><br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2137e41d-e714-4378-aa96-a1d98cc77979",
   "metadata": {},
   "source": [
    "7. Show that the following vectors are a span: <br>\n",
    "a.<br>\n",
    "$\n",
    "span\\begin{pmatrix}\n",
    "\\begin{bmatrix}1 \\\\ 1 \\\\ \\end{bmatrix}\n",
    "\\begin{bmatrix}1 \\\\ -1 \\\\ \\end{bmatrix}\n",
    "\\end{pmatrix}\n",
    "$\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "64e0ac1b-ddaa-476a-92a2-1103d913b840",
   "metadata": {},
   "source": [
    "Manual Solution:<br>\n",
    "$\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & | & x \\\\\n",
    "1 & -1 & | & y\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{}\n",
    "\\begin{bmatrix}\n",
    "\\begin{array}{cccc|c}\n",
    "1 & 1 & | & x & (R_1) \\\\\n",
    "1 & -1 & | & y & (R_2)\n",
    "\\end{array}\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{2} -\\text{R}_{1}}\n",
    "\\begin{bmatrix}\n",
    "\\begin{array}{cccc|c}\n",
    "1 & 1 & | & x & (R_1) \\\\\n",
    "0 & -2 & | & y - x & (R_2 - R_1)\n",
    "\\end{array}\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\frac{1}{-2}\\text{R}_{2}}\n",
    "\\begin{bmatrix}\n",
    "\\begin{array}{cccc|c}\n",
    "1 & 1 & | & x & (R_1) \\\\\n",
    "0 & 1 & | & \\frac{y - x}{-2} & \\left(\\frac{1}{-2}\\right)R_2\n",
    "\\end{array}\n",
    "\\end{bmatrix}\n",
    "$ <br>\n",
    "- The following vectors are a span.\n",
    "<br><br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8a2b1e44-ebc4-485b-9910-58d8cfc93f6c",
   "metadata": {},
   "source": [
    "b.<br>\n",
    "$\n",
    "span\\begin{pmatrix}\n",
    "\\begin{bmatrix}1 \\\\ 0 \\\\ 1\\end{bmatrix}\n",
    "\\begin{bmatrix}1 \\\\ 1 \\\\ 0\\end{bmatrix}\n",
    "\\begin{bmatrix}0 \\\\ 1 \\\\ 1\\end{bmatrix}\n",
    "\\end{pmatrix}\n",
    "$\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e1ede5c1-2ae5-4bf1-9ba0-b5a7681f77bc",
   "metadata": {},
   "source": [
    "Manual Solution: <br>\n",
    "\\begin{align*}\n",
    "a + b &= x \\\\\n",
    "b + c &= y \\\\\n",
    "a + c &= z\n",
    "\\end{align*}\n",
    "$\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 0 & | & x \\\\\n",
    "0 & 1 & 1 & | & y \\\\\n",
    "1 & 0 & 1 & | & z\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} - \\text{R}_{1}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 0 & | & x \\\\\n",
    "0 & 1 & 1 & | & y \\\\\n",
    "0 & -1 & 1 & | & z - x\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} + \\text{R}_{2}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 0 & | & x \\\\\n",
    "0 & 1 & 1 & | & y \\\\\n",
    "0 & 0 & 2 & | & y - x + z\n",
    "\\end{bmatrix}\n",
    "$\n",
    "<br>\n",
    "- The vectore are a span as long as \\(2\\) divides \\(y - x + z\\).\n",
    "<br><br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0f9ab1de-f1aa-491b-826e-2eef69337c6a",
   "metadata": {},
   "source": [
    "c. *Same given as B*<br>\n",
    "$\n",
    "span\\begin{pmatrix}\n",
    "\\begin{bmatrix}1 \\\\ 0 \\\\ 1\\end{bmatrix}\n",
    "\\begin{bmatrix}1 \\\\ 1 \\\\ 0\\end{bmatrix}\n",
    "\\begin{bmatrix}0 \\\\ 1 \\\\ 1\\end{bmatrix}\n",
    "\\end{pmatrix}\n",
    "$\n",
    "<br><br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f6b54a11-f3bc-4c34-ba1f-8c413683e007",
   "metadata": {},
   "source": [
    "Manual Solution: <br>\n",
    "\\begin{align*}\n",
    "a + b &= x \\\\\n",
    "b + c &= y \\\\\n",
    "a + c &= z\n",
    "\\end{align*}\n",
    "$\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 0 & | & x \\\\\n",
    "0 & 1 & 1 & | & y \\\\\n",
    "1 & 0 & 1 & | & z\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} - \\text{R}_{1}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 0 & | & x \\\\\n",
    "0 & 1 & 1 & | & y \\\\\n",
    "0 & -1 & 1 & | & z - x\n",
    "\\end{bmatrix}\n",
    "\\xrightarrow{\\text{R}_{3} + \\text{R}_{2}}\n",
    "\\begin{bmatrix}\n",
    "1 & 1 & 0 & | & x \\\\\n",
    "0 & 1 & 1 & | & y \\\\\n",
    "0 & 0 & 2 & | & y - x + z\n",
    "\\end{bmatrix}\n",
    "$\n",
    "<br>\n",
    "- The vectore are a span as long as \\(2\\) divides \\(y - x + z\\).\n",
    "<br><br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7ba9a8c1-5844-4be7-85e1-e476de63a3d2",
   "metadata": {},
   "source": [
    "8. Show that the following vectors are linearly independent:<br>\n",
    "a. <br>\n",
    "\\begin{equation}\n",
    "\\begin{bmatrix} 3 \\\\ -1 \\\\ 1 \\\\ -1 \\end{bmatrix}\n",
    "\\begin{bmatrix} -1 \\\\ 2 \\\\ 1 \\\\ -1 \\end{bmatrix}\n",
    "\\begin{bmatrix} 1 \\\\ 1 \\\\ 3 \\\\ 1 \\end{bmatrix}\n",
    "\\begin{bmatrix} -1 \\\\ -1 \\\\ 1 \\\\ 3 \\end{bmatrix}\n",
    "\\end{equation}<br>\n",
    "- m = 4 & n = 4; 4 $\\ngeq$ 4. By condidtion 3 & 4, the following vectors are linearly independent. <br>\n",
    "b. <br>\n",
    "\\begin{equation}\n",
    "\\begin{bmatrix} 0 \\\\ 0 \\\\ 0 \\\\ 1 \\end{bmatrix}\n",
    "\\begin{bmatrix} 0 \\\\ 0 \\\\ 2 \\\\ 1 \\end{bmatrix}\n",
    "\\begin{bmatrix} 0 \\\\ 3 \\\\ 2 \\\\ 1 \\end{bmatrix}\n",
    "\\begin{bmatrix} 4 \\\\ 3 \\\\ 2 \\\\ 1 \\end{bmatrix}\n",
    "\\end{equation}<br>\n",
    "- m = 4 & n = 4.<br>\n",
    "L1: 4z = 0; z = 0.<br>\n",
    "L2: 3w + 3z; w = 0.<br>\n",
    "L3: 2y + 2w + 2z = 0; y = 0.<br>\n",
    "L4: x + 0 + 0 + 0 = 0; x = 0.<br>\n",
    "Therefore, the vectors are linearly independent by condition 1.<br>\n",
    "\n",
    "c. <br>\n",
    "\\begin{equation}\n",
    "\\begin{bmatrix} 1 \\\\ -1 \\\\ 1 \\\\ 0 \\end{bmatrix}\n",
    "\\begin{bmatrix} -1 \\\\ 1 \\\\ 0 \\\\ 1 \\end{bmatrix}\n",
    "\\begin{bmatrix} 1 \\\\ 0 \\\\ 1 \\\\ -1 \\end{bmatrix}\n",
    "\\begin{bmatrix} 0 \\\\ 1 \\\\ -1 \\\\ 1 \\end{bmatrix}\n",
    "\\end{equation}<br>\n",
    "- m = 4 & n = 4. Therefore they are linearly independent by condidtion 4.<br>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "841ab4d3-38ad-4c94-9052-3a6f1dbc955d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}